services:
  - type: web
    name: fast-food-api
    env: python
    region: frankfurt  # ou oregon, singapore selon votre localisation
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fast-food-db
          property: connectionString
      - key: ADMIN_API_KEY
        generateValue: true
      - key: SMS_MOCK_MODE
        value: true
      - key: MANAGER_MOBILE
        value: +221777293282
      - key: CACHE_TYPE
        value: SimpleCache
      - key: CACHE_TTL
        value: 600

databases:
  - name: fast-food-db
    databaseName: fastfood
    plan: free
